import type { NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import axios from "axios";
import { useEffect, useState } from "react";
import ItemList from "../src/components/list";
import { BASE_URL } from "../src/lib/export/data";
import { Dimmer, Loader, Button, Icon } from "semantic-ui-react";
import Link from "next/link";
import * as S from "./styles";

const Home: NextPage = () => {
  const [data, setData] = useState<object>([]);
  const [loading, setLoading] = useState<boolean>(true);
  console.log(data);

  async function getData() {
    await axios
      .get(BASE_URL + "api/v1/products.json?brand=maybelline")
      .then((res) => {
        setData(res.data);
        setLoading(false);
      });
  }

  useEffect(() => {
    getData();
  }, []);

  return (
    <div className={styles.container}>
      <Head>
        <title>공부용</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* eslint-disable-next-line @next/next/link-passhref */}
      <Link href={"/view/login"}>
        <S.LoginButton>
          <Button color="google plus">
            <Icon name="google" /> Google
          </Button>
        </S.LoginButton>
      </Link>

      {loading ? (
        <Dimmer active inverted>
          <Loader inverted>Loading</Loader>
        </Dimmer>
      ) : (
        <ItemList item={data} />
      )}
    </div>
  );
};

export default Home;
